name: Update data through API

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
  schedule:
    - cron: '04 1,4,9,12,16,19,22 * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python dependencies
        run: |
          pip install -r 2022/requirements.txt
  
      - name: get data
        run: |-
          python 2022/update.py
        env: 
          TIPSPORT_USER: ${{ secrets.TIPSPORT_USER }}
          TIPSPORT_PASSWORD: ${{ secrets.TIPSPORT_PASSWORD }}
          TIPSPORT_PRODUCTID: ${{ secrets.TIPSPORT_PRODUCTID }}
          PROXY_SERVERS: ${{ secrets.PROXY_SERVERS }}

      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
